### ISSUE TITLE
No NetBSD support

### ISSUE THREAD

**Issue by gansm** [cross-platform-actions/action#1]
I am looking for a GitHub action build environment with NetBSD. It would be really great if this could be added to your portfolio.

**Comment by jacob-carlborg** [comment]
Yes, that's one of the platforms I would like to add support for. It's actually the next one on the list. Unfortunately it will be a bit more involved. NetBSD doesn't run on the Xhyve hypervisor which is currently being used by the other platforms. So far NetBSD I need to add support for QEMU.
