### ISSUE TITLE
Using custom images?

### ISSUE THREAD

**Issue by epsilon-0** [cross-platform-actions/action#10]
Can we use user provided QEMU qcow2 files? Currently the action only has OpenBSD 6.9 available, I have a setup which generates OpenBSD current images on a weekly basis and I want to be able to use those for the action.

Is this possible or supported?

Thanks!

**Comment by jacob-carlborg** [comment]
This is currently not supported. I guess it should be possible to add support for custom images. But it would put more responsibility on the user. The GitHub action currently expects some things in how the images are setup, to minimize work that needs to be done at runtime.

**Comment by epsilon-0** [comment]
My workflow is a bit different for generating the images (as I only need it for my own setup and don't need to be that general). I create a qemu guest image for openbsd manually and have a cron job on a host (gentoo) which runs `sysupgrade -s` inside the guest to update it to latest snapshot.

I use it for my github actions here - https://github.com/OBSD-Homelab/OBSD-Homelab/runs/6636599680?check_suite_focus=true. It is not the prettiest but it does get the job done. 

If more details could be given about what the requirements for the images are, it would be helpful in creating custom ones.

**Comment by jacob-carlborg** [comment]
> If more details could be given about what the requirements for the images are, it would be helpful in creating custom ones.

At a high level, this is what is required:

* A user called `runner`
* sshd, started at boot
* rsync
* Install public SSH key at boot time:
    1. Detect a secondary hard drive
    2. Mount the secondary hard drive as a FAT filesystem
    3. There will be a file called `KEYS` at the root of the hard drive, install that as an authorized key for the `runner` user

Then there are a couple of additional things, depending on what features of the action you're using. For all the details, see the [openbsd-builder](https://github.com/cross-platform-actions/openbsd-builder) repository. Here are some files of interest to look at in the repisotiry:

* [install.conf](https://github.com/cross-platform-actions/openbsd-builder/blob/312650b29c6938125db69e5150554fbf84fb29a1/resources/install.conf) - non-interactive install script
* [provision.h](https://github.com/cross-platform-actions/openbsd-builder/blob/312650b29c6938125db69e5150554fbf84fb29a1/resources/provision.sh) - provisioning run after the operating system has been installed

**Comment by jacob-carlborg** [comment]
BTW (for a wider audience), as far as I see it, there are three use cases for custom images:

* Additional software pre-installed. If this is of a supported operating system and version, this is the most likely use case to be working. The best way is to base the custom images on the official ones
* Running a non-supported version. If this is of a supported operating system it's likely to work but cannot be guaranteed (this is your use case)
* Running a non-supported operating system. This will not work

**Comment by epsilon-0** [comment]
So, I have forked the builder and made it upload daily snapshots for openbsd - https://github.com/OBSD-Homelab/openbsd-builder/releases/tag/current
For now I've removed some of the provisioning things that are there, as I didn't need them personally, but they should be easy enough to add back.

Maybe this can help add support for snapshots here.

**Comment by jacob-carlborg** [comment]
It's now possible [1] to use custom VM images, but only existing operating systems , architectures and versions are supported. 

Is this close enough to what you had in mind?

[1] https://github.com/cross-platform-actions/action/releases/tag/v0.18.0

**Comment by epsilon-0** [comment]
Yes, that should cover it. I'll try it out with the image that I am building here - https://github.com/OBSD-Homelab/openbsd-builder/releases/tag/current
It builds the latest rolling release of openbsd (called `current`) image every day. That image should be possible to use with this action, I'll let you know how it goes by eow.

**Comment by jacob-carlborg** [comment]
Closing this as fixed. See https://github.com/cross-platform-actions/action/issues/10#issuecomment-1666846767.
