### ISSUE TITLE
Increase memory in VM

### ISSUE THREAD

**Issue by straight-shoota** [cross-platform-actions/action#16]
Hi, I'm evaluating the use of this action for running CI for https://github.com/crystal-lang/crystal on FreeBSD. But the memory limit of 4GB restricts that (see https://github.com/crystal-lang/crystal/actions/runs/3943057224/jobs/6747446954).

I understand this is just an arbitrary limit. The runner has more to spare.

Would it be possible to make the memory setting configurable?

Perhaps it could also automatically delegate (almost) all memory available in the runner environment by default.

**Comment by jacob-carlborg** [comment]
> Would it be possible to make the memory setting configurable?

Yes, that should be doable.

**Comment by straight-shoota** [comment]
I suppose the same applies to `cpuCount`.

**Comment by jacob-carlborg** [comment]
> I suppose the same applies to cpuCount.

Please report a separate issue for that, so it's not forgotten.

**Comment by jacob-carlborg** [comment]
Awesome 👍.
