### ISSUE TITLE
Can't install packages in FreeBSD

### ISSUE THREAD

**Issue by Slackadays** [cross-platform-actions/action#18]
I'm trying to use this action for Free/Open/NetBSD builds for Clipboard (https://github.com/Slackadays/Clipboard). However, the prerequisites for FreeBSD are GCC 10/11/12 and CMake. I can't install these packages with `pkg` because the user isn't root, and I can't get root with `su` because the user isn't in the right group. Would it be possible to fix this? Currently if I can't install these packages then this action is incompatible with Clipboard. The same issue might be present in Open/NetBSD but I haven't checked those out yet. :)

**Comment by jacob-carlborg** [comment]
Hmm, that should definitely be possible. `sudo` is configured during installation [1], but I will investigate. Which version of FreeBSD are you using?

[1] https://github.com/cross-platform-actions/freebsd-builder/blob/db63308a4092613077532e1ca6a14ee732ec04b9/resources/provision.sh#L79-L86

**Comment by derobins** [comment]
I'm trying to use FreeBSD 13.1 and pkg is not found

**Comment by Slackadays** [comment]
I'm using FreeBSD 13.1 too, but somehow `pkg` was available and only complained that I wasn't root.

**Comment by jacob-carlborg** [comment]
Seems to work for me: https://github.com/cross-platform-actions/action/actions/runs/4018578271/jobs/6904364798.

**Comment by Slackadays** [comment]
Using `sudo pkg...` worked for me too, so I guess this issue is resolved.

https://github.com/Slackadays/Clipboard/actions/runs/4018816995/jobs/6904901916

**Comment by jacob-carlborg** [comment]
@derobins does it work for you?
