### ISSUE TITLE
OpenBSD 6.9 isn't provisioning

### ISSUE THREAD

**Issue by DrHyde** [cross-platform-actions/action#2]
See eg https://github.com/DrHyde/perl-modules-Palm-TreoPhoneCallDB/runs/3770059141

**Comment by jacob-carlborg** [comment]
You need to use the latest version of the action, 0.2.0: https://github.com/cross-platform-actions/action/releases/tag/v0.2.0.

**Comment by DrHyde** [comment]
Ah, so simple. Thanks!
