### ISSUE TITLE
No output until a job has finished

### ISSUE THREAD

**Issue by davidchisnall** [cross-platform-actions/action#27]
For different jobs I see slightly different behaviour, either no output until the job has finished or only the lines that have been emitted while watching the job are shown.  I have one NetBSD run that has gone for 16 minutes so far without producing any output and I have no idea if it's broken or just slow (it's the only QEMU one - is it using the KVM accelerator or just emulated mode?  If it's the latter, that would explain it).

**Comment by davidchisnall** [comment]
Actually, I think this might be an issue with GitHub's UI, unrelated to this action.

**Comment by jacob-carlborg** [comment]
> For different jobs I see slightly different behaviour, either no output until the job has finished or only the lines that have been emitted while watching the job are shown.

Yeah, I've noticed that too. I also think it's an issue with the UI. Does the raw logs show you the whole log?

> it's the only QEMU one - is it using the KVM accelerator or just emulated mode? If it's the latter, that would explain it

It's emulated. Unfortunately the Linux runners do not support hardware accelerated nested virtualization [1].

[1] https://github.com/actions/runner-images/issues/183.
