### ISSUE TITLE
NetBSD on xhyve?

### ISSUE THREAD

**Issue by davidchisnall** [cross-platform-actions/action#28]
It looks as if [NetBSD 9.x supports UEFI boot on bhyve](https://bentsukun.ch/posts/bhyve-netbsd/), is there a reason that it can't do the same on xhyve?

**Comment by jacob-carlborg** [comment]
I've tried installing NetBSD on xhyve, but for some reason it didn't work. I don't recall the exact details of why it didn't work.

But I do plan to support NetBSD on macOS runners using QEMU, that would allow hardware accelerated nested virtualization.

**Comment by davidchisnall** [comment]
From the link, it sounds as if putting this in `/boot.cfg` for NetBSD should let it work on xhyve:

```
menu=Boot normally:rndseed /var/db/entropy-file;userconf disable xhci*;boot
```

**Comment by jacob-carlborg** [comment]
It fails to boot the installer. It doesn't get to the userconf shell. Nothing happens.

**Comment by jacob-carlborg** [comment]
@davidchisnall I've added support for NetBSD on macOS runners. It's using QEMU as the hypervisor but it uses hardware accelerated virtualization.  Could you please give it a try with this commit: https://github.com/cross-platform-actions/action/commit/f3160be98978b352dc0622cd76ceda381ddbdb46.
