### ISSUE TITLE
Invalid operating system: netbsd

### ISSUE THREAD

**Issue by gansm** [cross-platform-actions/action#4]
I am trying to run a build on NetBSD. But unfortunately, I always received the error message:

`Invalid operating system: netbsd`

https://github.com/gansm/finalcut/runs/4183358693?check_suite_focus=true

**Comment by jacob-carlborg** [comment]
Yes, it's not ready yet. I used  the "Fix #1" syntax in the commit message which closes the issue automatically. But there are other repositories involved where I need to do some cleanup. Then I need to create a new releases/tags and you need to update to use the new tag, when it's available. I will hopefully get this done today or this weekend.

**Comment by gansm** [comment]
Excellent, it now works perfectly!

https://github.com/gansm/finalcut/runs/4201709257?check_suite_focus=true

**Comment by jacob-carlborg** [comment]
Perfect, thanks.

**Comment by jacob-carlborg** [comment]
Closed in https://github.com/cross-platform-actions/action/releases/tag/v0.3.0.
