### ISSUE TITLE
Add support for Linux running on a different architecture?

### ISSUE THREAD

**Issue by kobalicek** [cross-platform-actions/action#48]
At the moment it's possible to select a variety of BSDs, but it would be very useful to be able to run Linux, but on a non-x86 architecture (like ARM64). Because if I use just GHA offered runners and cross-platform-actions, the only possibility to test ARM64 is basically OpenBSD on ARM64.

Feel free to close if this is not planned.

**Comment by jacob-carlborg** [comment]
The plan was not to support Linux. See previous discussion in a different issue: https://github.com/cross-platform-actions/action/issues/43#issuecomment-1430957893.

**Comment by kobalicek** [comment]
Thanks for the answer, makes sense!

**Comment by jacob-carlborg** [comment]
I'll add the example from the other issue in the readme.
