### ISSUE TITLE
Using ::group:: to distinguish between steps?

### ISSUE THREAD

**Issue by kobalicek** [cross-platform-actions/action#49]
At the moment when a VM is run, there is a lot of messages, which are then combined with messages produced by the run script. GH actions provides a way how to group these messages by using `::group::` prefix during logging.

My question is whether it would be possible to use such groups to make the run script output easier to find. I have added a small screenshot from a workflow run where the content in the red rectangle is the actual code that runs in the VM (basically the content I'm most interested in), whereas all the output outside is from VM init/shutdown.

I would not mind having this feature optional, behind a flag, for example.

![image](https://user-images.githubusercontent.com/6491301/222839791-4aa589ec-23c6-4420-b7b1-ceb9e846b70b.png)

**Comment by jacob-carlborg** [comment]
Yes, that make sense. I've been thinking about this as well. A feature flag is not necessary. No information will be removed. It's just not visible by default.

**Comment by jacob-carlborg** [comment]
Now everything is hidden behind output groups except for the actual run command. I didn't bother in doing a more fined grained change.

**Comment by kobalicek** [comment]
Thanks, this is amazing!
