### ISSUE TITLE
NetBSD 9.3

### ISSUE THREAD

**Issue by manxorist** [cross-platform-actions/action#53]
Please update NetBSD to version 9.3.

**Comment by jacob-carlborg** [comment]
I tried to update earlier but something has changed slightly in the installation process, compared to 9.2, that caused the build to fail. If you're interested in contributing I could use the help. The repository that builds the NetBSD image is available here [1]. It uses Packer to build the image. 

[1] https://github.com/cross-platform-actions/netbsd-builder

**Comment by manxorist** [comment]
Fair enough. My todo list is already pretty long though, and NetBSD is not high priority for me either.

I may look into it eventually, but probably not in the next weeks. So, if someone else wants to take a look, go for it.

In any case, thank you building for cross-platform-actions! We use it to test building libopenmpt (https://github.com/OpenMPT/openmpt/) on OpenBSD and NetBSD (and also FreeBSD, but we also use Cirrus-CI for that).

**Comment by jacob-carlborg** [comment]
Was easier than I thought.

**Comment by manxorist** [comment]
Thanks, works for me!
