### ISSUE TITLE
SSH host port collision

### ISSUE THREAD

**Issue by PiotrSikora** [cross-platform-actions/action#59]
The SSH host port is hardcoded to `2847`, which prevents starting multiple instances of this action on the same host (e.g. when using the [`act`](https://github.com/nektos/act) tool).

**Comment by jacob-carlborg** [comment]
`act` is running inside a container. Can't you map the port to a different host port?

**Comment by PiotrSikora** [comment]
Digging deeper into this, it looks that `act` runs containers with `host` network by default, and changing it to the `bridge` network fixes the problem for me:

```
act -j openbsd --container-options "--privileged --network bridge"
```

Thanks for the suggestion!
