### ISSUE TITLE
VMs running via QEMU only expose SSE and SSE2 CPU features

### ISSUE THREAD

**Issue by kobalicek** [cross-platform-actions/action#60]
Even when the host machine supports more advanced instruction sets like AVX/AVX2 - VMs only expose SSE and SSE2. At the moment it's not possible to test AVX code in these VMs. Xhyve exposes features up to AVX, but not AVX2, even when the host supports these extensions.

Is there any plan to perhaps add an option that would influence how many CPU features would be provided to the guest machine? I think at least AVX as exposed by xhyve would be great.

**Comment by jacob-carlborg** [comment]
I can see if I can add more CPU features when using QEMU. As long as the OS boots I don't think it needs to be an option.

**Comment by jacob-carlborg** [comment]
Available now in [v0.19.0](https://github.com/cross-platform-actions/action/releases/tag/v0.19.0).
