### ISSUE TITLE
Default to forwarding CI environment variable

### ISSUE THREAD

**Issue by emarsden** [cross-platform-actions/action#71]
I check for the `CI `environment variable to disable "expensive" tests (for instance that generate a lot of network activity) on the GitHub CI workers. This is always set on a GitHub runner, running natively on in a container. 

It seems that it might be convenient for users to forward this environment variable into the VMs by default, or at least to make a reference to this in the README.md section on `environment_variables`.

**Comment by jacob-carlborg** [comment]
The `CI` and any environment variable starting with `GITHUB_` are already automatically forwarded. I've updated the readme to reflect this, in this "Input" section: https://github.com/cross-platform-actions/action#inputs.
