### ISSUE TITLE
Sync back files from VM skips all symlinks

### ISSUE THREAD

**Issue by mhuijgen** [cross-platform-actions/action#76]
It looks like rsync is ignoring symlinks during sync back.

```
Tearing down VM
  Syncing back files
  /usr/bin/rsync -uzrtopg runner@localhost:work/ /home/runner/work
  skipping non-regular file "my-project/"my-project/Server/node_modules/.bin/acorn"
  skipping non-regular file "my-project/"my-project/Server/node_modules/.bin/browserslist"
  skipping non-regular file "my-project/"my-project/Server/node_modules/.bin/color-support"
  skipping non-regular file "my-project/"my-project/Server/node_modules/.bin/conc"
```
Is this intentional or oversight?

If the latter, would it be possible to add -l to the rsync command used:
`       --links, -l              copy symlinks as symlinks
`

Looking at the rsync flags used to sync to the VM they are covered by the -a option
`/usr/bin/rsync -auzrtopg ......`

Using -a could be an option as well, but this also includes special device files (-D option) as well as symlinks.
If you want to keep using -a, I think its safe to remove rtopg options, since they are part of the -a option.

**Comment by mhuijgen** [comment]
Hi @jacob-carlborg,

Can I be of help by providing a PR that makes it use the same flags on both directions? It would really help us out of this rsync symlink issue would be fixed.

**Comment by jacob-carlborg** [comment]
> Can I be of help by providing a PR that makes it use the same flags on both directions? It would really help us out of this rsync symlink issue would be fixed.

@mhuijgen sure, I've completely forgotten about this.

**Comment by mhuijgen** [comment]
Created a PR #81
