### ISSUE TITLE
Update qemu to 8.2.0 for CVTPS2PD fix

### ISSUE THREAD

**Issue by kasper93** [cross-platform-actions/action#78]
We use QEMU emulation for stability, because xhyve hypervisor was failing half of the time last time we tried it. I've seen in recent release notes that there seems to be mitigation in place, so we might revisit that, but that's for another day.

For now I would like to request QEMU update to latest stable (8.2.0) as recently we hit the code which crashes QEMU. We get SIGBUS on valid code, see https://github.com/mpv-player/mpv/actions/runs/7377653152/job/20071858642

After painful debugging, because I couldn't reproduce locally, it seems to be CVTPS2PD instruction that fails. And sure enough after quick search the issue we see likely has been fixed in the recent stable release of QEMU (8.2.0)
Issue: https://gitlab.com/qemu-project/qemu/-/issues/1377
Fix: https://gitlab.com/qemu-project/qemu/-/commit/abd41884c530aa025ada253bf1a5bd0c2b808219

Thanks

**Comment by jacob-carlborg** [comment]
Yes. We tried to update to QEMU 8.1, but that broke OpenBSD. Hopefully 8.2 works better.
