### ISSUE TITLE
Increase qemu disk resources size

### ISSUE THREAD

**Issue by vnghia** [cross-platform-actions/action#85]
Hi, thank you for this action.

I am using `freebsd` on `linux` and got hit with `IO failure on output stream: No space left on device`. Is there anyway I can do to increase the size of the workspace ? Thank you very much!

**Comment by jacob-carlborg** [comment]
Do you know if that error is from the FreeBSD VM or the Linux runner? Do you have a link to the failing job?

**Comment by vnghia** [comment]
[Here](https://github.com/vnghia/nghe/actions/runs/8735441158/job/23968208168?pr=126#step:9:1303) for example. The falling line is rustc which only runs inside the VM. I tried to build an image with bigger size using `freebsd-builder` and `disk_size` variables but the job just hangs when trying to minimizing the image :/ Only 15G works but that is still not enough for rustc. 20G and 30G take already 2 hours and still not finished yet.

**Comment by jacob-carlborg** [comment]
When building the image it will fill up the disk with zeros to be able to minimize the disk. It's probably that that takes time. You can try removing that step [1]. But the VM image might become larger. Also when running the action it will covert the image to raw format. Than means the it will expand the disk on the runner. Not sure if that will fit. Previously the runners had 16 GB in storage but they have recently been upgraded. 

[1] https://github.com/cross-platform-actions/freebsd-builder/blob/0e5ede653f51b23575a04cf612d5eeb487667785/resources/cleanup.sh#L22

**Comment by vnghia** [comment]
Perfect. I have to remove `minimize_disk` and `minimize_swap`. The final image size is ~2gb which is good for me.
