### ISSUE TITLE
Error syncing back files

### ISSUE THREAD

**Issue by yanecc** [cross-platform-actions/action#86]
runner: ubuntu-latest
operating_system: freebsd
architecture: arm64
version: "14.0"
shell: sh

https://github.com/yanecc/MockGPT/actions/runs/8910624672/job/24470242079#step:3:177

**Comment by jacob-carlborg** [comment]
What happens if you rerun the job, do you get the same error?

**Comment by yanecc** [comment]
> What happens if you rerun the job, do you get the same error?

I figured out the problem, I need to use the sudo to install.
