### ISSUE TITLE
FreeBSD 14.1

### ISSUE THREAD

**Issue by manxorist** [cross-platform-actions/action#87]
FreeBSD 14.1 is already supported by https://github.com/cross-platform-actions/freebsd-builder, but I am not aware of a method to use it before cross-platform-action itself gets updated. Maybe I am missing something obvious here?

**Comment by jacob-carlborg** [comment]
There are a few steps that need to be done to add support for a new version of an OS. A new release in the builder repository need to be created. Then the `version.ts` file need to be updated and finally a new release in this repository.

**Comment by jacob-carlborg** [comment]
Fixed in https://github.com/cross-platform-actions/action/commit/6acac3ca1b632aa762721d537dea32398ba0f2b1.
